application: sandy-helping-hands
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /stylesheets
  static_dir: stylesheets
- url: /icons
  static_dir: icons
- url: /javascript
  static_dir: javascript
- url: /closure/goog
  static_dir: closure_lib/closure/goog
- url: /closure/css
  static_dir: closure_lib/closure/goog/css

- url: .*
  script: main.app
  secure: always
libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
builtins:
  - appstats: on
  - remote_api: on
