# application: sandy-disaster-recovery # ** do not commit this line **
application: sandy-helping-hands
version: 153
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /stylesheets
  static_dir: stylesheets
  expiration: "7d"
- url: /icons
  static_dir: icons
  expiration: "7d"
- url: /javascript
  static_dir: javascript
  expiration: "7d"
- url: /closure/goog
  static_dir: closure_lib/closure/goog
  expiration: "7d"
- url: /closure/css
  static_dir: closure_lib/closure/goog/css
  expiration: "7d"
- url: /assets
  static_dir: assets
  expiration: "7d"

- url: .*
  script: main.app
  secure: always
libraries:
- name: webapp2
  version: "2.3"
- name: jinja2
  version: latest
builtins:
  - deferred: on
  - appstats: on
  - remote_api: on
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?google$
- ^(.*/)?google_appengine$
