// This file was autogenerated by calcdeps.py
goog.addDependency("../../../javascript/form.js", ['sandy.form'], ['goog.dom']);
goog.addDependency("../../../javascript/deps.js", [], []);
goog.addDependency("../../../javascript/compiled_form.js", [], []);
goog.addDependency("../../../javascript/compiled_demo.js", [], []);
goog.addDependency("../../../javascript/compiled_main.js", [], []);
goog.addDependency("../../../javascript/map.js", ['sandy.map'], ['goog.dom', 'goog.events.EventType', 'goog.string', 'goog.ui.Dialog', 'goog.ui.Dialog.ButtonSet', 'goog.ui.Option', 'goog.ui.Select']);
goog.addDependency("../../../javascript/externs.js", [], []);
goog.addDependency("../../../javascript/demo.js", ['sandy.demo'], ['goog.dom', 'goog.events.EventType', 'goog.string', 'goog.ui.Dialog', 'goog.ui.Dialog.ButtonSet', 'goog.ui.Option', 'goog.ui.Select', 'sandy.map']);
goog.addDependency("../../../javascript/main.js", ['sandy.main'], ['goog.dom', 'goog.events.EventType', 'goog.json', 'goog.net.XhrIo', 'goog.string', 'goog.ui.Dialog', 'goog.ui.Dialog.ButtonSet', 'goog.ui.Option', 'goog.ui.Select', 'goog.style', 'sandy.map']);
