// This file was autogenerated by calcdeps.py
goog.addDependency("../../../javascript/form.js", [], ['goog.dom']);
goog.addDependency("../../../javascript/deps.js", [], []);
goog.addDependency("../../../javascript/map.js", ['sandy.map'], ['goog.dom', 'goog.events.EventType', 'goog.string', 'goog.ui.Dialog', 'goog.ui.Dialog.ButtonSet', 'goog.ui.Option', 'goog.ui.Select']);
goog.addDependency("../../../javascript/main.js", ['sandy.main'], ['goog.dom', 'goog.events.EventType', 'goog.string', 'goog.ui.Dialog', 'goog.ui.Dialog.ButtonSet', 'goog.ui.Option', 'goog.ui.Select']);
